### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.25 ~1 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.125 ~1 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0 ~1 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.125 ~1 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.625 ~0.875 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.5 ~0.875 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.375 ~0.875 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.5 ~0.875 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.75 ~0.75 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.625 ~0.75 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.875 ~0.625 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.75 ~0.625 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.875 ~0.5 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.75 ~0.5 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-1 ~0.25 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.875 ~0.25 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-1 ~0.125 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.875 ~0.125 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-1 ~-0.125 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.875 ~-0.125 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-1 ~-0.25 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.875 ~-0.25 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.875 ~-0.5 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.75 ~-0.5 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.75 ~-0.625 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.625 ~-0.625 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.625 ~-0.75 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.5 ~-0.75 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.375 ~-0.75 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.5 ~-0.75 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.375 ~-0.875 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.25 ~-0.875 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~-0.125 ~-0.875 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0 ~-0.875 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.125 ~-0.875 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.88f,0.05f,1f],scale:0.65f} ~0.25 ~-0.875 ~0 0 0 0 0 1 force @a




