### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-0.3333333 ~1.3333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-0.1666667 ~1.3333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~0 ~1.3333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~0.1666667 ~1.3333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-0.8333333 ~1.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-0.6666667 ~1.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~0.5 ~1.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~0.6666667 ~1.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-1 ~1 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~0.8333333 ~1 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-1.1666667 ~0.8333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~1 ~0.8333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-1.1666667 ~0.6666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~1 ~0.6666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-1.3333333 ~0.3333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~1.1666667 ~0.3333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-1.3333333 ~0.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~1.1666667 ~0.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-1.3333333 ~-0.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~1.1666667 ~-0.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-1.3333333 ~-0.3333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~1.1666667 ~-0.3333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-1.1666667 ~-0.6666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~1 ~-0.6666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-1 ~-0.8333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~0.8333333 ~-0.8333333 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-0.8333333 ~-1 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-0.6666667 ~-1 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~0.5 ~-1 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~0.6666667 ~-1 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-0.5 ~-1.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-0.3333333 ~-1.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~-0.1666667 ~-1.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~0 ~-1.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~0.1666667 ~-1.1666667 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0f,0f,0f],scale:0.65f} ~0.3333333 ~-1.1666667 ~0 0 0 0 0 1 force @a