### Particle Image Function
### Version: 1.0.4
### Width: 30
### Height: 30
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^1.3333333 ^0 ^0.2222222 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.67f,0.38f,0.04f],scale:0.75f} ^1.2222222 ^0 ^-0.2222222 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.67f,0.38f,0.04f],scale:0.75f} ^1.1111111 ^0 ^1.1111111 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.67f,0.38f,0.04f],scale:0.75f} ^1 ^0 ^-0.7777778 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^0.8888889 ^0 ^0.1111111 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.67f,0.38f,0.04f],scale:0.75f} ^0.5555556 ^0 ^-1 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^0.3333333 ^0 ^0.7777778 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^0.3333333 ^0 ^1.3333333 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^0.2222222 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^-0.4444444 ^0 ^-0.2222222 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^-0.4444444 ^0 ^0.5555556 0 0 0 0 1 force @a
