### Particle Image Function
### Version: 1.0.4
### Width: 30
### Height: 30
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[0.67f,0.38f,0.04f],scale:0.75f} ^1.3 ^0 ^-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^1.2 ^0 ^0.3 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.67f,0.38f,0.04f],scale:0.75f} ^1 ^0 ^0.8 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^0.8 ^0 ^-1.1 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.67f,0.38f,0.04f],scale:0.75f} ^0.7 ^0 ^0.6 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.67f,0.38f,0.04f],scale:0.75f} ^0.6 ^0 ^-1.4 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.67f,0.38f,0.04f],scale:0.75f} ^0.6 ^0 ^-0.1 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^0.5 ^0 ^1.2 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.67f,0.38f,0.04f],scale:0.75f} ^0.1 ^0 ^-1.3 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^0.1 ^0 ^-0.9 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.56f,0.32f,0.02f],scale:0.75f} ^-0.1 ^0 ^0.7 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.67f,0.38f,0.04f],scale:0.75f} ^-0.3 ^0 ^-0.1 0 0 0 0 1 force @a
